package org.example.expensetracker.entity;

public enum Category {
    FOOD_GROCERIES,
    TRANSPORTATION,
    HOUSING_UTILITIES,
    ENTERTAINMENT,
    HEALTHCARE,
    INSURANCE,
    PERSONAL_CARE,
    CLOTHING,
    EDUCATION,
    SUBSCRIPTIONS_MEMBERSHIPS,
    TRAVEL_VACATIONS,
    GIFTS_DONATIONS,
    SAVINGS_INVESTMENTS,
    DEBT_PAYMENTS,
    MISCELLANEOUS,
}
