server:
  port: ${SERVER_PORT:9090}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ADDRESS:http://localhost:8761/eureka}

spring:
  application:
    name: cloud-gateway
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "${FRONTEND_URI:http://localhost:5173}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10
            key-resolver: "#{@remoteAddressResolver}"
  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: 24b2eb99d299917874343b569d70c9805cc12135ca962235ee5d34552d84073e

logging:
  file:
    name: /logs/cloud-gateway.log
    path: /logs