server:
  port: 9090


spring:
  application:
    name: cloud-gateway
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org:
      springframework: debug

jwt:
  secret: 24b2eb99d299917874343b569d70c9805cc12135ca962235ee5d34552d84073e