apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eureka-server-ft
spec:
  selector:
    matchLabels:
      app: eureka-server-ft
  template:
    metadata:
      labels:
        app: eureka-server-ft
    spec:
      containers:
        - name: eureka-server-ft
          image: danil2110/eureka-server-ft

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server-ft
spec:
  clusterIP: None
  selector:
    app: eureka-server-ft
  ports:
    - port: 8761
      name: eureka-server-ft

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server-ft-lb
spec:
  type: NodePort
  selector:
    app: eureka-server-ft
  ports:
    - port: 80
      targetPort: 8761