apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-web-client
  labels:
    app: ft-web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-web-client
  template:
    metadata:
      labels:
        app: ft-web-client
    spec:
      containers:
        - name: ft-web-client
          image: danil2110/finance-tracker-web-client
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://cloud-gateway-svc"

---

apiVersion: v1
kind: Service
metadata:
  name: ft-web-client-svc
spec:
  selector:
    app: ft-web-client
  ports:
    - port: 80
      targetPort: 5173
  type: NodePort