apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql
spec:
  selector:
    matchLabels:
      app: psql
  serviceName: psql
  replicas: 1
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - name: psql
        image: postgres:16.2
        ports:
        - containerPort: 5432
          name: psql
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: financetracker
        volumeMounts:
        - name: psql-persistent-storage
          mountPath: /var/lib/psql
      volumes:
        - name: psql-persistent-storage
          persistentVolumeClaim:
            claimName: psql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: psql
spec:
  clusterIP: None
  selector:
    app: psql
  ports:
  - port: 5432
